# https://pagescms.org/docs/configuration/

media:
  - name: images
    label: Images
    input: public
    output: /

content:
  - name: posts
    label: Posts
    path: posts
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: body
        label: Body
        type: rich-text
        require: true
      - name: tags
        label: Tags
        type: text
        list: true
      - name: draft
        label: Draft
        type: boolean
        default: true
