name: Blog Post Generator

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled

jobs:
  generate_post:
    if: contains(github.event.issue.labels.*.name, 'post')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - uses: actions/checkout@v4
      - name: Generate a new post
        id: generate_post
        env:
          TITLE: "${{ github.event.issue.title }}"
          BODY: "${{ github.event.issue.body }}"
          STATE: "${{ github.event.issue.state }}"
          LABELS_JSON: "${{ toJSON(github.event.issue.labels) }}"
          CREATED_AT: "${{ github.event.issue.created_at }}"
        run: |
          FRONT_MATTER="---\n"
          FRONT_MATTER+="title: \"$TITLE\"\n"

          DRAFT_STATUS=$([ "$STATE" == "open" ] && echo "true" || echo "false")
          FRONT_MATTER+="draft: $DRAFT_STATUS\n"

          TAGS_YAML=$(echo "$LABELS_JSON" \
            | jq -r '
              [.[].name | select(startswith("tag:")) | ltrimstr("tag:")]
              | if length > 0 then
                  "tags:\n" + (map("  - " + .) | join("\n"))
                else
                  ""
                end
            ')
          if [ -n "$TAGS_YAML" ]; then
            FRONT_MATTER+="$TAGS_YAML\n"
          fi

          FRONT_MATTER+="---\n"

          DATE=${CREATED_AT%%T*} # YYYY-MM-DD
          SAFE_TITLE=$(echo "$TITLE" | sed -e 's/[[:space:]]\+/-/g' -e 's#[\/\\:*?"<>|]#-#g' | sed -E 's/--+/-/g' | sed -E 's/^-|-$//g')
          FILE_PATH="posts/${DATE}_${SAFE_TITLE}.md"
          mkdir -p posts
          echo "file_path=${FILE_PATH}" >> $GITHUB_OUTPUT

          echo -e "${FRONT_MATTER}\n${BODY}" > "$FILE_PATH"
      - name: Commit changes
        env:
          FILE_PATH: "${{ steps.generate_post.outputs.file_path }}"
          NUMBER: "${{ github.event.issue.number }}"
          ACTION: "${{ github.event.action }}"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add "$FILE_PATH"
          git commit -m "Issue #$NUMBER $ACTION: update post"
          git push origin HEAD
