name: Update posts

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task build
      - name: Extract latest pubDate from feed.rss
        id: pubdate
        run: |
          PUBDATE=$(grep -oPm1 "(?<=<pubDate>)[^<]+" _site/feed.rss)
          PUBDATE_ISO=$(python3 -c "from email.utils import parsedate_to_datetime; print(parsedate_to_datetime('$PUBDATE').isoformat())")
          echo "pubdate_iso=$PUBDATE_ISO" >> $GITHUB_OUTPUT
      - name: Get latest git commit date
        id: gitdate
        run: |
          GITDATE=$(git log -1 --format=%cI)
          echo "gitdate=$GITDATE" >> $GITHUB_OUTPUT
      - name: Compare pubDate and latest commit
        if: steps.pubdate.outputs.pubdate_iso > steps.gitdate.outputs.gitdate
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git commit --allow-empty -m "Update posts: ${{ steps.pubdate.outputs.pubdate_iso }}"
          git push origin HEAD
