name: Update submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
          submodules: true
          persist-credentials: false
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Update submodules"
          git push origin HEAD
