name: Update submodules

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Update submodules"
          git push origin HEAD
